In [14]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [15]:
dataset = pd.read_csv('H:\\machien learning\\Markov Academy\\Machine learning & Python\\DataSets\\creditcard\\creditcard.csv')

In [18]:
dataset.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62      0  
1  0.125895 -0.008983  0.014724    2.69      0  
2 -0.139097 -0.055353 -0.059752  378.66      0  
3 -0.221929  0.062723  0.061458  123.50      0  
4  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

In [21]:
from sklearn.preprocessing import StandardScaler

In [22]:
dataset['new amount'] = StandardScaler().fit_transform(dataset[['Amount']])


In [23]:
dataset.columns

Index(['Time', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10',
       'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20',
       'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'Amount',
       'Class', 'new amount'],
      dtype='object')

In [24]:
dataset = dataset.drop(['Amount','Time'] , axis = 1)

In [25]:
dataset['Class'].value_counts()

0    284315
1       492
Name: Class, dtype: int64

In [26]:
fraud_index = dataset[dataset['Class']==1].index

In [27]:
number_fraud = len(fraud_index)

In [28]:
number_fraud

492

In [29]:
normal_index = dataset[dataset['Class']==0].index

In [30]:
random_normal_index = np.random.choice(normal_index , number_fraud)

In [31]:
len(random_normal_index)

492

In [32]:
balanced_index = np.concatenate([random_normal_index , fraud_index])

In [33]:
balnced_data = dataset.iloc[balanced_index]

In [34]:
balnced_data

V1        V2        V3        V4        V5        V6        V7  \
196825 -1.306891 -0.686800  1.256177 -1.684931  0.926138 -0.005343  0.116951   
88984   0.684004 -1.449180  0.175201  0.122298 -0.683761  0.978786 -0.403574   
147834 -0.847868  0.183013  0.564268 -2.717593 -1.102121 -0.443982 -0.015386   
65906   1.151862 -0.715869  1.373740  0.683740 -1.450090  0.522712 -1.247206   
111980  1.142674  0.145938  0.093640  1.227673 -0.086691 -0.424421  0.227832   
...          ...       ...       ...       ...       ...       ...       ...   
279863 -1.927883  1.125653 -4.518331  1.749293 -1.566487 -2.010494 -0.882850   
280143  1.378559  1.289381 -5.004247  1.411850  0.442581 -1.326536 -1.413170   
280149 -0.676143  1.126366 -2.213700  0.468308 -1.120541 -0.003346 -2.234739   
281144 -3.113832  0.585864 -5.399730  1.817092 -0.840618 -2.943548 -2.208002   
281674  1.991976  0.158476 -2.583441  0.408670  1.151147 -0.096695  0.223050   

              V8        V9       V10  ...       V21       V22       V23  \
196825  0.238252 -1.522069 -0.102048  ... -0.275490 -0.769892 -0.055388   
88984   0.240836  1.359571 -0.615631  ... -0.123048 -0.767885 -0.321054   
147834 -1.727592  1.676729 -3.088162  ...  1.559122 -0.474386 -1.143948   
65906   0.440432 -0.270928  0.831022  ... -0.348284 -0.418048  0.138179   
111980 -0.071749  0.214630 -0.098460  ...  0.003598  0.111126 -0.137966   
...          ...       ...       ...  ...       ...       ...       ...   
279863  0.697211 -2.064945 -5.587794  ...  0.778584 -0.319189  0.639419   
280143  0.248525 -1.127396 -3.232153  ...  0.370612  0.028234 -0.145640   
280149  1.210158 -0.652250 -3.463891  ...  0.751826  0.834108  0.190944   
281144  1.058733 -1.632333 -5.245984  ...  0.583276 -0.269209 -0.456108   
281674 -0.068384  0.577829 -0.888722  ... -0.164350 -0.295135 -0.072173   

             V24       V25       V26       V27       V28  Class  new amount  
196825  0.171792  0.645113  0.245826 -0.066564  0.058468      0   -0.033582  
88984  -1.243583  0.117958  1.028672 -0.080246  0.047922      0    0.886177  
147834 -0.211519  1.470699 -0.148113  0.309709  0.153001      0    0.846196  
65906   0.148148  0.114912 -0.387347  0.099300  0.029006      0   -0.301214  
111980  0.086760  0.739024 -0.248223  0.016974  0.014054      0   -0.219893  
...          ...       ...       ...       ...       ...    ...         ...  
279863 -0.294885  0.537503  0.788395  0.292680  0.147968      1    1.206024  
280143 -0.081049  0.521875  0.739467  0.389152  0.186637      1   -0.350191  
280149  0.032070 -0.739695  0.471111  0.385107  0.194361      1   -0.041818  
281144 -0.183659 -0.328168  0.606116  0.884876 -0.253700      1    0.626302  
281674 -0.450261  0.313267 -0.289617  0.002988 -0.015309      1   -0.183191  

[984 rows x 30 columns]

In [35]:
from sklearn.model_selection import train_test_split

In [36]:
train,test = train_test_split(balnced_data , test_size=.3)

In [37]:
x_train = train.drop('Class' , axis=1)
y_train = train['Class']

x_test= test.drop('Class' , axis=1)
y_test = test['Class']

In [38]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix

In [39]:
lr = LogisticRegression()

In [40]:
lr.fit(x_train,y_train)

LogisticRegression()

In [41]:
y_pred = lr.predict(x_test)

In [42]:
confusion_matrix(y_test,y_pred)

array([[153,   0],
       [ 11, 132]], dtype=int64)

In [43]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score
from sklearn.metrics import precision_recall_fscore_support
from sklearn.metrics import precision_recall_curve
from sklearn.metrics import classification_report
from sklearn.metrics import roc_curve
from sklearn.metrics import roc_curve
from sklearn.metrics import auc
from sklearn.metrics import roc_auc_score

In [44]:
AccScore = accuracy_score(y_test, y_pred, normalize=False)

In [45]:
AccScore

285

In [46]:
F1Score = f1_score(y_test, y_pred, average='micro') 

In [47]:
F1Score

0.9628378378378378

In [48]:
RecallScore = recall_score(y_test, y_pred, average='micro') 

In [49]:
RecallScore

0.9628378378378378

In [50]:
PrecisionScore = precision_score(y_test, y_pred, average='micro') 

In [51]:
PrecisionScore

0.9628378378378378

In [52]:
PrecisionRecallScore = precision_recall_fscore_support(y_test, y_pred, average='micro')

In [53]:
PrecisionRecallScore

(0.9628378378378378, 0.9628378378378378, 0.9628378378378378, None)

In [54]:
PrecisionValue, RecallValue, ThresholdsValue = precision_recall_curve(y_test,y_pred)

In [55]:
PrecisionValue, RecallValue, ThresholdsValue

(array([0.48310811, 1.        , 1.        ]),
 array([1.        , 0.92307692, 0.        ]),
 array([0, 1], dtype=int64))

In [56]:
ClassificationReport = classification_report(y_test,y_pred)

In [57]:
ClassificationReport

'              precision    recall  f1-score   support\n\n           0       0.93      1.00      0.97       153\n           1       1.00      0.92      0.96       143\n\n    accuracy                           0.96       296\n   macro avg       0.97      0.96      0.96       296\nweighted avg       0.97      0.96      0.96       296\n'

In [58]:
fprValue, tprValue, thresholdsValue = roc_curve(y_test,y_pred)

In [59]:
fprValue, tprValue, thresholdsValue

(array([0., 0., 1.]),
 array([0.        , 0.92307692, 1.        ]),
 array([2, 1, 0], dtype=int64))

In [60]:
fprValue2, tprValue2, thresholdsValue2 = roc_curve(y_test,y_pred)
AUCValue = auc(fprValue2, tprValue2)


In [61]:
fprValue2, tprValue2, thresholdsValue2

(array([0., 0., 1.]),
 array([0.        , 0.92307692, 1.        ]),
 array([2, 1, 0], dtype=int64))

In [62]:
AUCValue

0.9615384615384616

In [63]:
ROCAUCScore = roc_auc_score(y_test,y_pred, average='micro') 

In [64]:
ROCAUCScore

0.9615384615384616

In [100]:
from sklearn import svm, datasets
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV

iris = datasets.load_iris()
parameters = {'kernel':('linear', 'rbf'), 'C':[1,2,3,4,5]}
svc = svm.SVC(gamma="scale")
clf = GridSearchCV(svc, parameters, cv=5)
clf.fit(x_train,y_train)



GridSearchCV(cv=5, estimator=SVC(),
             param_grid={'C': [1, 2, 3, 4, 5], 'kernel': ('linear', 'rbf')})

In [101]:
from sklearn.svm import SVR
from sklearn.model_selection import GridSearchCV

In [102]:
model = SVR(epsilon=.1 , gamma = 'auto')
params = { 'kernel':('linear' , 'rbf')  ,  'c':[1,2,3,4,5] }

In [103]:
gridsearchmodel = GridSearchCV(model,params, cv = 2  ,return_train_score= True )

In [104]:
gridsearchmodel.fit(x_train , y_train)

ValueError: Invalid parameter c for estimator SVR(gamma='auto'). Check the list of available parameters with `estimator.get_params().keys()`.

In [105]:
from sklearn.svm import SVR
SelectedModel = SVR(epsilon=0.1,gamma='auto')
SelectedParameters = {'kernel':('linear', 'rbf'), 'C':[1,2,3,4,5]}


GridSearchModel = GridSearchCV(SelectedModel,SelectedParameters, cv = 2,return_train_score=True)
GridSearchModel.fit(x_train, y_train)
sorted(GridSearchModel.cv_results_.keys())
GridSearchResults = pd.DataFrame(GridSearchModel.cv_results_)[['mean_test_score', 'std_test_score', 'params' , 'rank_test_score' , 'mean_fit_time']]

# Showing Results
print('All Results are :\n', GridSearchResults )
print('Best Score is :', GridSearchModel.best_score_)
print('Best Parameters are :', GridSearchModel.best_params_)
print('Best Estimator is :', GridSearchModel.best_estimator_)



All Results are :
    mean_test_score  std_test_score                        params  \
0         0.475258        0.036858  {'C': 1, 'kernel': 'linear'}   
1         0.715104        0.012392     {'C': 1, 'kernel': 'rbf'}   
2         0.471904        0.039408  {'C': 2, 'kernel': 'linear'}   
3         0.711982        0.004666     {'C': 2, 'kernel': 'rbf'}   
4         0.472213        0.038579  {'C': 3, 'kernel': 'linear'}   
5         0.703232        0.001214     {'C': 3, 'kernel': 'rbf'}   
6         0.472931        0.038599  {'C': 4, 'kernel': 'linear'}   
7         0.696874        0.003989     {'C': 4, 'kernel': 'rbf'}   
8         0.472683        0.038837  {'C': 5, 'kernel': 'linear'}   
9         0.695158        0.004890     {'C': 5, 'kernel': 'rbf'}   

   rank_test_score  mean_fit_time  
0                6       0.717721  
1                1       0.009999  
2               10       1.289149  
3                2       0.016002  
4                9       2.136353  
5               

In [109]:
SelectedModel = SVR(epsilon=0.1,gamma='auto')
SelectedParameters = {'kernel':('linear', 'rbf'), 'C':[1,2,3,4,5]}
#=======================================================================
RandomizedSearchModel = RandomizedSearchCV(SelectedModel,SelectedParameters, n_iter=20 ,cv = 2,return_train_score=True)
RandomizedSearchModel.fit(x_train, y_train)
sorted(RandomizedSearchModel.cv_results_.keys())
RandomizedSearchResults = pd.DataFrame(RandomizedSearchModel.cv_results_)[['mean_test_score', 'std_test_score', 'params' , 'rank_test_score' , 'mean_fit_time']]

# Showing Results
print('All Results are :\n', RandomizedSearchResults )
print('Best Score is :', RandomizedSearchModel.best_score_)
print('Best Parameters are :', RandomizedSearchModel.best_params_)
print('Best Estimator is :', RandomizedSearchModel.best_estimator_)


F:\anaconda\lib\site-packages\sklearn\model_selection\_search.py:278: UserWarning: The total space of parameters 10 is smaller than n_iter=20. Running 10 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(


All Results are :
    mean_test_score  std_test_score                        params  \
0         0.475258        0.036858  {'kernel': 'linear', 'C': 1}   
1         0.715104        0.012392     {'kernel': 'rbf', 'C': 1}   
2         0.471904        0.039408  {'kernel': 'linear', 'C': 2}   
3         0.711982        0.004666     {'kernel': 'rbf', 'C': 2}   
4         0.472213        0.038579  {'kernel': 'linear', 'C': 3}   
5         0.703232        0.001214     {'kernel': 'rbf', 'C': 3}   
6         0.472931        0.038599  {'kernel': 'linear', 'C': 4}   
7         0.696874        0.003989     {'kernel': 'rbf', 'C': 4}   
8         0.472683        0.038837  {'kernel': 'linear', 'C': 5}   
9         0.695158        0.004890     {'kernel': 'rbf', 'C': 5}   

   rank_test_score  mean_fit_time  
0                6       0.767200  
1                1       0.014501  
2               10       1.352144  
3                2       0.015980  
4                9       2.364093  
5               

In [110]:
for i in range(0,1):
    if i == 0 :
        SelectedModel = SVR(epsilon=0.1,gamma='auto')
        SelectedParameters = {'kernel':('linear', 'rbf'), 'C':[1,2,3,4,5]}


        GridSearchModel = GridSearchCV(SelectedModel,SelectedParameters, cv = 2,return_train_score=True)
        GridSearchModel.fit(x_train, y_train)
        sorted(GridSearchModel.cv_results_.keys())
        GridSearchResults = pd.DataFrame(GridSearchModel.cv_results_)[['mean_test_score', 'std_test_score', 'params' , 'rank_test_score' , 'mean_fit_time']]

        # Showing Results
        print('All Results are :\n', GridSearchResults )
        print('Best Score is :', GridSearchModel.best_score_)
        print('Best Parameters are :', GridSearchModel.best_params_)
        print('Best Estimator is :', GridSearchModel.best_estimator_)
        # Showing Results
        print('All Results are :\n', GridSearchResults )
        print('Best Score is :', GridSearchModel.best_score_)
        print('Best Parameters are :', GridSearchModel.best_params_)
        print('Best Estimator is :', GridSearchModel.best_estimator_)
    if i == 1 :
        SelectedModel = SVR(epsilon=0.1,gamma='auto')
        SelectedParameters = {'kernel':('linear', 'rbf'), 'C':[1,2,3,4,5]}
        #=======================================================================
        RandomizedSearchModel = RandomizedSearchCV(SelectedModel,SelectedParameters, n_iter=2 ,cv = 2,return_train_score=True)
        RandomizedSearchModel.fit(x_train, y_train)
        sorted(RandomizedSearchModel.cv_results_.keys())
        RandomizedSearchResults = pd.DataFrame(RandomizedSearchModel.cv_results_)[['mean_test_score', 'std_test_score', 'params' , 'rank_test_score' , 'mean_fit_time']]

        # Showing Results
        print('All Results are :\n', RandomizedSearchResults )
        print('Best Score is :', RandomizedSearchModel.best_score_)
        print('Best Parameters are :', RandomizedSearchModel.best_params_)
        print('Best Estimator is :', RandomizedSearchModel.best_estimator_)

All Results are :
    mean_test_score  std_test_score                        params  \
0         0.475258        0.036858  {'C': 1, 'kernel': 'linear'}   
1         0.715104        0.012392     {'C': 1, 'kernel': 'rbf'}   
2         0.471904        0.039408  {'C': 2, 'kernel': 'linear'}   
3         0.711982        0.004666     {'C': 2, 'kernel': 'rbf'}   
4         0.472213        0.038579  {'C': 3, 'kernel': 'linear'}   
5         0.703232        0.001214     {'C': 3, 'kernel': 'rbf'}   
6         0.472931        0.038599  {'C': 4, 'kernel': 'linear'}   
7         0.696874        0.003989     {'C': 4, 'kernel': 'rbf'}   
8         0.472683        0.038837  {'C': 5, 'kernel': 'linear'}   
9         0.695158        0.004890     {'C': 5, 'kernel': 'rbf'}   

   rank_test_score  mean_fit_time  
0                6       0.788254  
1                1       0.013493  
2               10       1.372425  
3                2       0.015483  
4                9       2.427976  
5               

In [115]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC, LinearSVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import Perceptron
from sklearn.linear_model import SGDClassifier
from sklearn.tree import DecisionTreeClassifier

In [123]:
for i in range(0,10):
    if i == 0 :
        logreg = LogisticRegression()
        logreg.fit(x_train, y_train)
        Y_pred = logreg.predict(x_test)
        acc_log = round(logreg.score(x_train, y_train) * 100, 2)
        acc_log
    if i == 1 :
        coeff_df = pd.DataFrame(balnced_data.columns.delete(0))
        coeff_df.columns = ['Feature']
        coeff_df["Correlation"] = pd.Series(logreg.coef_[0])
        coeff_df.sort_values(by='Correlation', ascending=False)
    if i == 2 :
        svc = SVC()
        svc.fit(x_train, y_train)
        Y_pred = svc.predict(x_test)
        acc_svc = round(svc.score(x_train, y_train) * 100, 2)
        acc_svc
    if i == 3 :
        knn = KNeighborsClassifier(n_neighbors = 3)
        knn.fit(x_train, y_train)
        Y_pred = knn.predict(x_test)
        acc_knn = round(knn.score(x_train, y_train) * 100, 2)
        acc_knn
    if i == 4 :
        gaussian = GaussianNB()
        gaussian.fit(x_train, y_train)
        Y_pred = gaussian.predict(x_test)
        acc_gaussian = round(gaussian.score(x_train, y_train) * 100, 2)
        acc_gaussian
    if i == 5 :
        perceptron = Perceptron()
        perceptron.fit(x_train, y_train)
        Y_pred = perceptron.predict(x_test)
        acc_perceptron = round(perceptron.score(x_train, y_train) * 100, 2)
        acc_perceptron
    if i == 6 :
        linear_svc = LinearSVC()
        linear_svc.fit(x_train, y_train)
        Y_pred = linear_svc.predict(x_test)
        acc_linear_svc = round(linear_svc.score(x_train, y_train) * 100, 2)
        acc_linear_svc
    if i == 7 :
        sgd = SGDClassifier()
        sgd.fit(x_train, y_train)
        Y_pred = sgd.predict(x_test)
        acc_sgd = round(sgd.score(x_train, y_train) * 100, 2)
        acc_sgd
    if i == 8 :
        decision_tree = DecisionTreeClassifier()
        decision_tree.fit(x_train, y_train)
        Y_pred = decision_tree.predict(x_test)
        acc_decision_tree = round(decision_tree.score(x_train, y_train) * 100, 2)
        acc_decision_tree
    if i == 9 :
        random_forest = RandomForestClassifier(n_estimators=100)
        random_forest.fit(x_train, y_train)
        Y_pred = random_forest.predict(x_test)
        random_forest.score(x_train, y_train)
        acc_random_forest = round(random_forest.score(x_train, y_train) * 100, 2)
        acc_random_forest

F:\anaconda\lib\site-packages\sklearn\svm\_base.py:976: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "


In [139]:
logreg = LogisticRegression()
logreg.fit(x_train, y_train)
Y_pred = logreg.predict(x_test)
acc_log = round(logreg.score(x_train, y_train) * 100, 2)
acc_log

95.35

In [140]:
coeff_df = pd.DataFrame(balnced_data.columns.delete(0))
coeff_df.columns = ['Feature']
coeff_df["Correlation"] = pd.Series(logreg.coef_[0])
coeff_df.sort_values(by='Correlation', ascending=False)


Feature  Correlation
28  new amount     0.968219
3           V5     0.868707
21         V23     0.665276
10         V12     0.541384
4           V6     0.302931
27       Class     0.292410
0           V2     0.283770
18         V20     0.178250
2           V4     0.154116
1           V3     0.057208
24         V26     0.029415
14         V16    -0.004941
22         V24    -0.005512
20         V22    -0.140771
17         V19    -0.148021
6           V8    -0.195268
26         V28    -0.206125
23         V25    -0.248467
12         V14    -0.260771
25         V27    -0.342570
5           V7    -0.414388
15         V17    -0.503686
16         V18    -0.558800
19         V21    -0.565181
8          V10    -0.583500
7           V9    -0.678309
9          V11    -0.727951
13         V15    -1.090518
11         V13    -1.277698

In [141]:
svc = SVC()
svc.fit(x_train, y_train)
Y_pred = svc.predict(x_test)
acc_svc = round(svc.score(x_train, y_train) * 100, 2)
acc_svc

93.75

In [124]:
knn = KNeighborsClassifier(n_neighbors = 3)
knn.fit(x_train, y_train)
Y_pred = knn.predict(x_test)
acc_knn = round(knn.score(x_train, y_train) * 100, 2)
acc_knn

96.37

In [138]:
gaussian = GaussianNB()
gaussian.fit(x_train, y_train)
Y_pred = gaussian.predict(x_test)
acc_gaussian = round(gaussian.score(x_train, y_train) * 100, 2)
acc_gaussian


array([[153,   0],
       [ 11, 132]], dtype=int64)

In [127]:
perceptron = Perceptron()
perceptron.fit(x_train, y_train)
Y_pred = perceptron.predict(x_test)
acc_perceptron = round(perceptron.score(x_train, y_train) * 100, 2)
acc_perceptron

94.91

In [128]:
linear_svc = LinearSVC()
linear_svc.fit(x_train, y_train)
Y_pred = linear_svc.predict(x_test)
acc_linear_svc = round(linear_svc.score(x_train, y_train) * 100, 2)
acc_linear_svc

F:\anaconda\lib\site-packages\sklearn\svm\_base.py:976: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "


95.49

In [129]:
sgd = SGDClassifier()
sgd.fit(x_train, y_train)
Y_pred = sgd.predict(x_test)
acc_sgd = round(sgd.score(x_train, y_train) * 100, 2)
acc_sgd

92.88

In [130]:
decision_tree = DecisionTreeClassifier()
decision_tree.fit(x_train, y_train)
Y_pred = decision_tree.predict(x_test)
acc_decision_tree = round(decision_tree.score(x_train, y_train) * 100, 2)
acc_decision_tree

100.0

In [131]:
random_forest = RandomForestClassifier(n_estimators=100)
random_forest.fit(x_train, y_train)
Y_pred = random_forest.predict(x_test)
random_forest.score(x_train, y_train)
acc_random_forest = round(random_forest.score(x_train, y_train) * 100, 2)
acc_random_forest

100.0

In [132]:
svr = SVR()
svr.fit(x_train, y_train)
Y_pred = svr.predict(x_test)
acc_svr = round(svc.score(x_train, y_train) * 100, 2)
acc_svr

93.75

In [134]:
models = pd.DataFrame({
    'Model': ['Support Vector Machines', 'KNN', 'Logistic Regression', 
              'Random Forest', 'Naive Bayes', 'Perceptron', 
              'Stochastic Gradient Decent', 'Linear SVC', 
              'Decision Tree' , 'linear SVR'],
    'Score': [acc_svc, acc_knn, acc_log, 
              acc_random_forest, acc_gaussian, acc_perceptron, 
              acc_sgd, acc_linear_svc, acc_decision_tree ,acc_svr ]})
models.sort_values(by='Score', ascending=False)

Model   Score
3               Random Forest  100.00
8               Decision Tree  100.00
1                         KNN   96.37
7                  Linear SVC   95.49
2         Logistic Regression   95.35
5                  Perceptron   94.91
0     Support Vector Machines   93.75
9                  linear SVR   93.75
6  Stochastic Gradient Decent   92.88
4                 Naive Bayes   90.12